// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCADdZ8C47GZCBdn1y5BmFAOJXqRalEdw8',
    appId: '1:39114810974:web:b65879bf63710eb06836cf',
    messagingSenderId: '39114810974',
    projectId: 'ishikawasightseeingapp',
    authDomain: 'ishikawasightseeingapp.firebaseapp.com',
    storageBucket: 'ishikawasightseeingapp.appspot.com',
    measurementId: 'G-EXVZMH1YFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2wKlxBR-tlC8RUoxjv1XRQB-tmW2UK7g',
    appId: '1:39114810974:android:72f28e3d49e327056836cf',
    messagingSenderId: '39114810974',
    projectId: 'ishikawasightseeingapp',
    storageBucket: 'ishikawasightseeingapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOcXJ0ewb4FXvQf-UdodwjDjDBoKKHQBM',
    appId: '1:39114810974:ios:c2611e212f946d166836cf',
    messagingSenderId: '39114810974',
    projectId: 'ishikawasightseeingapp',
    storageBucket: 'ishikawasightseeingapp.appspot.com',
    iosBundleId: 'com.example.isikawaSightseeingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOcXJ0ewb4FXvQf-UdodwjDjDBoKKHQBM',
    appId: '1:39114810974:ios:a431c6c6cc0bc9916836cf',
    messagingSenderId: '39114810974',
    projectId: 'ishikawasightseeingapp',
    storageBucket: 'ishikawasightseeingapp.appspot.com',
    iosBundleId: 'com.example.isikawaSightseeingApp.RunnerTests',
  );
}
